
spring:
  jpa:
    show-sql: true
    open-in-view: true
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_NAME:postgres}
    hikari:
      schema: yan
  flyway:
    locations: classpath:db.migration
    enabled: true
    validate-on-migrate: true
    baseline-on-migrate: true
    default-schema: yan
  mvc:
    problem-details:
      enabled: true
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-circular-references: true
  kafka:
    bootstrap-servers: localhost:9093
    consumer:
      auto-offset-reset: earliest
    listener:
      ack-mode: record
  application:
    name: testtask

kafka:
  topics:
    good: good
    order-event: order-event
delays:
  order-event:
    send: 60000

logging:
  level:
    org.springframework:
      orm.jpa: DEBUG
      transaction: DEBUG
server:
  port: 8081